import React, { PropTypes } from 'react';

const { func } = PropTypes;

export default {
  onBlur: func,
  onChange: func,
  onClick: func,
  onCompositionEnd: func,
  onCompositionStart: func,
  onCompositionUpdate: func,
  onContextMenu: func,
  onCopy: func,
  onCut: func,
  onDoubleClick: func,
  onDrag: func,
  onDragEnd: func,
  onDragEnter: func,
  onDragExit: func,
  onDragLeave: func,
  onDragOver: func,
  onDragStart: func,
  onDrop: func,
  onFocus: func,
  onInput: func,
  onKeyDown: func,
  onKeyPress: func,
  onKeyUp: func,
  onMouseDown: func,
  onMouseEnter: func,
  onMouseLeave: func,
  onMouseMove: func,
  onMouseOut: func,
  onMouseOver: func,
  onMouseUp: func,
  onPaste: func,
  onScroll: func,
  onSelect: func,
  onSubmit: func,
  onTouchCancel: func,
  onTouchEnd: func,
  onTouchMove: func,
  onTouchStart: func,
  onWheel: func
};
